### ISSUE TITLE
Create incoming in inbox without reference in work queue (do when CR 4288 is available)

### ISSUE THREAD

**Issue by rowe42** [it-at-m/swim#122]
Due to [[SWIM] Erstellung von Eingangsdokumenten für neue Schriftstücke im Postkorb](https://jira.muenchen.de/browse/EAKTE-4288) the SOAP-Call `CreateIncomingFromInboxGI` has been changed such that parameter `referrednumber` is no longer mandatory. That means that the incoming can be created without being assigned to a procedure ("Vorgang" within a "Akte"). It will also not show up as a new activity in the work queue, but only in the tab "Erfasste Eingänge" in the inbox.

For this to work, we need to
- create the contentObject in the inbox as we already do in `DmsAdapter.createContentObjectInInbox`
- return the COO of the newly created contentObject (which will be available after issue #118 is done)
- call the method `CreateIncomingFromInboxGI` (i.e. `POST incomingFromInbox` in the REST-EAI), handing in the COO of the target inbox in `inboxid` and the COO of the previously created contentObject in `contentid`, but NOT anything in `referrednumber`

Example:

```
curl -X 'POST' \
  'https://<dmsresteai-test>/api/incomingFromInbox' \
  -H 'accept: application/json' \
  -H 'x-anwendung: SWIM' \
  -H 'userlogin: <userlogin>' \
  -H 'Authorization: Basic <auth>' \
  -H 'Content-Type: application/json' \
  -d '{
  "inboxid": "COO.2150.9151.1.1055658",
  "contentid": "COO.2150.9151.1.1160458",
  "shortname": "MeinDokument20250319",
  "filesubj": "myfilesub"
}'
```

This issue depends on the completion of #118.

**Comment by rowe42** [comment]
Question is: How should this behavior be triggered? The options:
- do it when `metadata-subject` is set to true in the usecase
- introduce a separate parameter in the `application.yml`, e.g. `incoming-from-inbox:true`

Maybe we should also be able to trigger this through a parameter within the Metadata-JSON?

Let's discuss.

**Comment by simonhir** [comment]
After discussion:
- Type: `inbox_incoming` (which can also me resolved via metadata file)
- Refactor use case properties to nested:
```
  use-cases:
    - name: # required
      type: # required, see section "Type"
      coo-source: # required, see section "Coo source"
      context:
        username: # user under which the DMS action is executed
        joboe: # used to resolve user role under which the DMS action is executed, default role if not defined
        jobposition: # used to resolve user role under which the DMS action is executed, default role if not defined
      target_resolution: # propably?
        target-coo: # for coo-source static
        filename-coo-pattern: # for coo-source filename
        filename-to-coo: # for coo-source filename_map
        filename-name-pattern: # for coo-source filename_name
      incoming:
        incoming-name-pattern: # overwrite Incoming name via Regex pattern, only applies to type incoming_object
        verify-procedure-name-pattern: # verifies target procedure name matches this pattern, only applies to type incoming_object
      content_object:
        metadata-subject: # enables incoming subject be built from metadata file
        filename-overwrite-pattern: # overwrite ContentObject name via Regex pattern
```
